version: "3"

services:
  app:
    image: pythonoccutils-img:latest
    environment:
      - XAUTH_ADD_ARG=${XAUTH_ADD_ARG}
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/dri/:/dev/dri
      - ./..:/wsp
    security_opt:
      - seccomp:unconfined
    network_mode: host

